# Generated by Django 4.2.1 on 2023-05-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldenThougthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('Motywacja', 'Motywacja'), ('Melancholia', 'Melancholia'), ('Na poprawę nastroju', 'Na poprawę nastroju')], max_length=50)),
                ('body', models.TextField()),
                ('added_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
