# Generated by Django 4.2.1 on 2023-05-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_thought', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldenthougthdata',
            options={'verbose_name': 'Golden Thougth', 'verbose_name_plural': 'Golden Thougths'},
        ),
    ]
