# Generated by Django 4.2.1 on 2023-06-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_thought', '0002_alter_goldenthougthdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenthougthdata',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
